#!/usr/bin/python
# lintory - keep track of computers and licenses
# Copyright (C) 2008-2009 Brian May
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from lintory import models

def process(hardware):
    nested_list = models.hardware.objects.filter(installed_on = hardware)
    for nested in nested_list:
        print hardware, nested
        if nested.location is None:
            nested.location = hardware.location
        if nested.owner is None:
            nested.owner = hardware.owner
        if nested.user is None:
            nested.user = hardware.user
        nested.save()
        process(nested)


hardware_list = models.hardware.objects.filter(installed_on__isnull = True)
for hardware in hardware_list:
    print "---"
    process(hardware)
