#!/usr/bin/python
from lintory import models

def update(value):
    if value is None:
        return value

    try:
        v = models.party.objects.get(
                eparty=value,
        )
    except models.party.DoesNotExist, e:
        v = models.party()
        v.name = u"%s"%(value)
        v.eparty = value
        v.save()

    print v
    return v

for location in models.location.objects.all():
    location.owner = update(location.old_owner)
    location.user  = update(location.old_user)
    location.save()

for hardware in models.hardware.objects.all():
    hardware.owner = update(hardware.old_owner)
    hardware.user  = update(hardware.old_user)
    hardware.save()

for license in models.license.objects.all():
    license.owner = update(license.old_owner)
    license.save()

for hardware_task in models.hardware_task.objects.all():
    hardware_task.assigned = update(hardware_task.old_assigned)
    hardware_task.save()
