#!/usr/bin/python
# lintory - keep track of computers and licenses
# Copyright (C) 2008-2009 Brian May
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.core.management import setup_environ
from inventory import settings
setup_environ(settings)

from lintory import models

def process(hardware):
    nested_list = models.hardware.objects.filter(installed_on = hardware)
    for nested in nested_list:
        print hardware, nested

        updated = False
        if nested.location != hardware.location:
            nested.location = hardware.location
            updated = True
        if nested.owner != hardware.owner:
            nested.owner = hardware.owner
            updated = True
        if nested.user != hardware.user:
            nested.user = hardware.user
            updated = True

        if updated:
            nested.save()

        process(nested)


hardware_list = models.hardware.objects.filter(installed_on__isnull = True)
for hardware in hardware_list:
    print "---"
    process(hardware)
