#!/bin/bash
set -e

case "$1" in
    (purge)
        for i in /var/lib/lintory /var/lib/lintory/data
        do
            if dpkg-statoverride --list $i >/dev/null 2>&1
            then
                dpkg-statoverride --remove $i
            fi
        done
        rm -rf /usr/share/lintory/static
        rm /etc/lintory/settings.py*
        rm /var/lib/lintory/lintory.db*
    ;;
esac


#DEBHELPER#

